### ISSUE TITLE
关于加载ip_vs_ca后两个问题.

### ISSUE THREAD

**Issue by dongzy0905** [yubo/ip_vs_ca#1]
你好,目前发现两个问题
1. realserver加载model后 监听端口程序重启,相应端口无法释放的问题
2. realserver测试当作nginx代理层，不加载model可以curl得到正常数据,加载model后会提示出现empty reply from server,静态页面和php页面都会出现empty reply from server！nginx相关access日志 http code # **499**
日志如下：
- \- [12/Apr/2016:18:03:07 +0800] "GET /index.html HTTP/1.1" **499** 0 "**10.3.18.12:8999**" "-" "-" "118.118.118.118" "/index.html" 0.000 - "Mo
  zilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"

谢谢！

**Comment by yubo** [comment]
1 fixed: https://github.com/yubo/ip_vs_ca/commit/41af06da7f7550908a264ecefaebde07fc6da28b
2 没能重现这个问题，能提供详细信息吗？
