### ISSUE TITLE
关于加载ip_vs_ca后的一个问题（Go程序端口无法监听，提示address family not supported by protocol）

### ISSUE THREAD

**Issue by qiukeren** [yubo/ip_vs_ca#2]
```
package main

import (
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    http.HandleFunc("/", NotFoundHandler)
    err := http.ListenAndServe(":8889", nil)
    if err != nil {
        fmt.Println(err)
    }
}

var a = []byte("hello?")

func NotFoundHandler(w http.ResponseWriter, r *http.Request) {
    body, _ := ioutil.ReadAll(r.Body)
    fmt.Printf("%#v\n", string(body))
    defer r.Body.Close()
}
```

go语言小程序，在没有加载模块时，会正常运行，加载模块后，会提示http监听端口失败，具体信息为

```
accept tcp [::]:8889: address family not supported by protocol
```

其他类型的小程序也有类似的问题：

```
accept tcp [::]:1990: accept4: address family not supported by protocol
```

**Comment by snailq** [comment]
遇到同样的问题

**Comment by zhangkunnops** [comment]
+1，同样的错误
加载ip_vs_ca后，机器上运行的另外一个程序出现如下错误：
2017/01/09 10:49:42 cfg.go:121: read config file: cfg.json successfully
2017/01/09 10:49:42 http.go:75: listening :1988
2017/01/09 10:49:42 http.go:76: accept tcp 0.0.0.0:1988: accept4: address family not supported by protocol

**Comment by zhangkunnops** [comment]
@yubo 能否帮忙看下是哪里的问题吗？

**Comment by zhangkunnops** [comment]
问题已经找到了，是TCP_OPTION参数的问题，由254修改为200后问题解决。

**Comment by yubo** [comment]
问题已解决 https://github.com/yubo/ip_vs_ca/commit/41af06da7f7550908a264ecefaebde07fc6da28b

**Comment by yubo** [comment]
https://github.com/yubo/ip_vs_ca/commit/8d81a6d48ce9dad1590944457d1630117f9179fd
