### ISSUE TITLE
CentOS 7.2 build失败

### ISSUE THREAD

**Issue by iclouding** [yubo/ip_vs_ca#4]
[root@dev01 src]# make -f linux.mk
make -C /lib/modules/`uname -r`/build M=/root/lvs/ip_vs_ca/src modules
make[1]: 进入目录“/usr/src/kernels/3.10.0-327.el7.x86_64”
scripts/Makefile.build:44: /root/lvs/ip_vs_ca/src/Makefile: 没有那个文件或目录
make[2]: *** 没有规则可以创建目标“/root/lvs/ip_vs_ca/src/Makefile”。 停止。
make[1]: *** [_module_/root/lvs/ip_vs_ca/src] 错误 2
make[1]: 离开目录“/usr/src/kernels/3.10.0-327.el7.x86_64”
make: *** [modules] 错误 2

求助，CentOS7.2 怎么编译TOA内核？

**Comment by yubo** [comment]
1 可以 ln -s linux.mk Makefile ; make
2 或者更新下 https://github.com/yubo/ip_vs_ca/commit/dd0f50c14209bb0012f28d3cb26135f79ce481ba
