### ISSUE TITLE
make问题

### ISSUE THREAD

**Issue by damonzheng** [yubo/ip_vs_ca#6]
试了很多次make以后都是MODPOST 0 modules，以下是make信息，请求指点。🙏

[root@test src]# make
make -C /usr/src/kernels/3.10.0-514.26.2.el7.x86_64 M=/root/ip_vs_ca/src modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'

[root@test src]# make V=1
make -C /usr/src/kernels/3.10.0-514.26.2.el7.x86_64 M=/root/ip_vs_ca/src modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /root/ip_vs_ca/src/.tmp_versions ; rm -f /root/ip_vs_ca/src/.tmp_versions/*
make -f scripts/Makefile.build obj=/root/ip_vs_ca/src
(cat /dev/null; ) > /root/ip_vs_ca/src/modules.order
make -f ./scripts/Makefile.modpost
  find /root/ip_vs_ca/src/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m -a -i ./Module.symvers -I /root/ip_vs_ca/src/Module.symvers  -o /root/ip_vs_ca/src/Module.symvers  -w -s -T -
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.26.2.el7.x86_64'

**Comment by yubo** [comment]
系统当前内核版本是3.10.0-514.26.2.el7.x86_64　吗？

**Comment by damonzheng** [comment]
这个是装了了新的kernel-devel

**Comment by damonzheng** [comment]
![image](https://user-images.githubusercontent.com/12538637/28759917-2a6ff5fa-75d5-11e7-8471-49b4132f0b08.png)

**Comment by damonzheng** [comment]
![image](https://user-images.githubusercontent.com/12538637/28759931-4859c852-75d5-11e7-9f1f-35f27297e403.png)

**Comment by yubo** [comment]
是否修改过

**Comment by damonzheng** [comment]
大概是我这边 编译环境的问题，我把Kbuild.default改成 Kbuild 就顺利编译了  😁

**Comment by yubo** [comment]
src/cmakelists.txt里有更详细的过程
