### ISSUE TITLE
RS can not fetch real client ip

### ISSUE THREAD

**Issue by qzj** [yubo/ip_vs_ca#7]
RS  centos 7.2 , kernel 3.10.0-327, your description the kernel 3.10.0-237.4.5 looks wrong. And accourding the readme we use this module , but nginx still get the local ip not real ip.

**Comment by yubo** [comment]
you can use tcpdump to get tcpopt code, Make sure the value is equal to 200 (default), or you can change it
```
echo 255 > /proc/sys/net/ca/tcpopt_addr
```

**Comment by qzj** [comment]
thanks ,  echo 254 > /proc/sys/net/ca/tcpopt_addr  , and get the right remote ip.

**Comment by xnile** [comment]
同样遇到这个问题，但是我在rs机器上没有/proc/sys/net/ca/tcpopt_addr 这个文件，请问什么原因。

**Comment by qzj** [comment]
If  not found /proc/sys/net/ca/tcpopt_addr , please check that modprobe ip_vs_ca correctly.
